<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UetpSeeder extends Seeder
{
    public function run()
    {
        // Primeiramente semeamos os usuários
        $usuarioModel = new \App\Models\UsuarioModel();

        $grupoUsuarioModel = new \App\Models\GrupoUsuarioModel();


        $usuarios = [
            [
                "nome" => "ANANINDEUA 01",
                "local" => "Ananindeua",
                "login" => "ananindeua1",
                "email" => "profsilmamlmiranda@gmail.com",
                "password" => "paseec2231",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ANANINDEUA 02",
                "local" => "Ananindeua",
                "login" => "ananindeua2",
                "email" => "taniavaleria2015@hotmail.com",
                "password" => "paseec2232",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ANANINDEUA 03",
                "local" => "Ananindeua",
                "login" => "ananindeua3",
                "email" => "leonilmonteiroalmada@gmail.com",
                "password" => "paseec2233",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ANANINDEUA 04",
                "local" => "Ananindeua",
                "login" => "ananindeua4",
                "email" => "itqananindeua4@gmail.com",
                "password" => "paseec2234",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ANANINDEUA 05",
                "local" => "Ananindeua",
                "login" => "ananindeua5",
                "email" => "itqextensao5ana@gmail.com",
                "password" => "paseec2235",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ANTÔNIO BARRETO",
                "local" => "Belém",
                "login" => "abarreto",
                "email" => "inez.vitorino@teacherculturapa.com.br",
                "password" => "paseec2236",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "BARCARENA",
                "local" => "Barcarena",
                "login" => "barcarena",
                "email" => "claudiapafor@yahoo.com.br",
                "password" => "paseec2237",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "BRAGANÇA",
                "local" => "Bragança",
                "login" => "braganca",
                "email" => "itq.braganca@gmail.com",
                "password" => "paseec2238",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "BUJARU",
                "local" => "Bujaru",
                "login" => "bujaru",
                "email" => "pra.ednaimbiriba@gmail.com",
                "password" => "paseec2238",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "CAMETÁ",
                "local" => "Cametá",
                "login" => "cameta",
                "email" => "anaclara04nov@gmail.com",
                "password" => "paseec2239",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "CTMQ/PA/01",
                "local" => "Belém",
                "login" => "ctmqpa1",
                "email" => "contatoctmqpara@gmail.com",
                "password" => "paseec2240",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ICOARACI",
                "local" => "Icoaraci",
                "login" => "icoaraci",
                "email" => "prmarcosantos20@gmail.com",
                "password" => "paseec2241",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/001 – Pedreira ",
                "local" => "Belém",
                "login" => "itqpa01",
                "email" => "itqpedreira@gmail.com",
                "password" => "paseec2204",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/002 - Marambaia",
                "local" => "Belém",
                "login" => "itqpa02",
                "email" => "erivaldo.270558@gmail.com",
                "password" => "paseec2205",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/003 – Cremação ",
                "local" => "Belém",
                "login" => "itqpa03",
                "email" => "silviafrota@hotmail.com",
                "password" => "paseec2206",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/004 – Ananindeua 7",
                "local" => "Ananindeua",
                "login" => "itqpa04",
                "email" => "suzanaecqueiroz@gmail.com",
                "password" => "paseec2207",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/005 – CTMQ ",
                "local" => "Belém",
                "login" => "itqpa05",
                "email" => "misaelandrade@gmail.com",
                "password" => "paseec2208",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/006 – Ananindeua 4",
                "local" => "Ananindeua",
                "login" => "itqpa06",
                "email" => "itqananindeua4@gmail.com",
                "password" => "paseec2209",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/007 – Marabá II",
                "local" => "Marabá",
                "login" => "itqpa07",
                "email" => "itqindependencia337@hotmail.com",
                "password" => "paseec2210",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/008 – Breves",
                "local" => "Breves",
                "login" => "itqpa08",
                "email" => "marcosoliveira43970@gmail.com",
                "password" => "paseec2211",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/009 – Parauapebas ",
                "local" => "Parauapebas",
                "login" => "itqpa09",
                "email" => "joelmaandrade03@gmail.com",
                "password" => "paseec2212",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/010 – Igarapé Miri",
                "local" => "Igarapé Miri",
                "login" => "itqpa10",
                "email" => "itqigmiri@gmail.com",
                "password" => "paseec2213",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/011 - Itaituba",
                "local" => "Itaituba",
                "login" => "itqpa11",
                "email" => "alcioneqd@gmail.com",
                "password" => "paseec2214",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/012 - Guamá",
                "local" => "Belém",
                "login" => "itqpa12",
                "email" => "itq13abelem@gmail.com",
                "password" => "paseec2215",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/013 – Tapanã ",
                "local" => "Belém",
                "login" => "itqpa13",
                "email" => "mariarosaferreiradeoliveira@gmail.com",
                "password" => "paseec2216",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/014 – Vigia ",
                "local" => "Vigia",
                "login" => "itqpa14",
                "email" => "pastorairacildapalheta@gmail.com",
                "password" => "paseec2217",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/015 - Castanhal",
                "local" => "Castanhal",
                "login" => "itqpa15",
                "email" => "ana-claudia1000@hotmail.com",
                "password" => "paseec2218",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/016 – São Clemente",
                "local" => "São Clemente",
                "login" => "itqpa16",
                "email" => "jobsonift@gmail.com",
                "password" => "paseec2219",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/017 – Maguary ",
                "local" => "Belém",
                "login" => "itqpa17",
                "email" => "prwilsoncarlos@hotmail.com",
                "password" => "paseec2220",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/018 – Barcarena 2",
                "local" => "Barcarena",
                "login" => "itqpa18",
                "email" => "carla.melero05@gmail.com",
                "password" => "paseec2221",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/019 – Parauapebas 2",
                "local" => "Parauapebas",
                "login" => "itqpa19",
                "email" => "esterlitasantos104@gmail.com",
                "password" => "paseec2222",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/020 – Ponta de Pedras",
                "local" => "Ponta de Pedras",
                "login" => "itqpa20",
                "email" => "a-ires2010@hotmail.com",
                "password" => "paseec2223",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/021 – Tomé Açu",
                "local" => "Tomé Açu",
                "login" => "itqpa21",
                "email" => "itqtomeacu@gmail.com",
                "password" => "paseec2224",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/022 - Soure",
                "local" => "Soure",
                "login" => "itqpa22",
                "email" => "luciamedeirosgoreti@gmail.com",
                "password" => "paseec2225",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/023 – Capitão Poço",
                "local" => "Capitão Poço",
                "login" => "itqpa23",
                "email" => "raymonteiro619@gmail.com",
                "password" => "paseec2226",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/024 - Altamira",
                "local" => "Altamira",
                "login" => "altamira",
                "email" => "lumafrazao@hotmail.com",
                "password" => "paseec2230",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "ITQ/PA/025 - Paragominas",
                "local" => "Paragominas",
                "login" => "paragominas",
                "email" => "marlene.santos35@hotmail.com",
                "password" => "paseec2247",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "JURUNAS",
                "local" => "Belém",
                "login" => "jurunas",
                "email" => "itqjurunas8@gmail.com",
                "password" => "paseec2242",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "MAGUARY",
                "local" => "Belém",
                "login" => "maguary",
                "email" => "prwilsoncarlos@hotmail.com",
                "password" => "paseec2243",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "MARABÁ 01",
                "local" => "Marabá",
                "login" => "maraba1",
                "email" => "itq.maraba@gmail.com",
                "password" => "paseec2244",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "MARITUBA 01",
                "local" => "Marituba",
                "login" => "marituba1",
                "email" => "pramarciacardoso2@gmail.com",
                "password" => "paseec2245",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "MQTI/PA/01",
                "local" => "Belém",
                "login" => "mqtipa01",
                "email" => "vaniapereiramx@gmail.com",
                "password" => "paseec2227",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "MQTI/PA/02",
                "local" => "Parauapebas",
                "login" => "mqtipa02",
                "email" => "joelmaandrade03@gmsil.com",
                "password" => "paseec2228",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "MQTI/PA/03",
                "local" => "Cametá",
                "login" => "mqtipa03",
                "email" => "mjoseferreira46@yahoo.com.br",
                "password" => "paseec2229",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "PANORAMA XXI",
                "local" => "Belém",
                "login" => "panorama",
                "email" => "cleitonjorge40@gmail.com",
                "password" => "paseec2246",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "REDENÇÃO",
                "local" => "Redenção",
                "login" => "redencao",
                "email" => "dsilva885@gmail.com",
                "password" => "paseec2248",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "SACRAMENTA",
                "local" => "Belém",
                "login" => "sacramenta",
                "email" => "geyza_leal@hotmail.com",
                "password" => "paseec2249",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "SANTA IZABEL",
                "local" => "Santa Izabel",
                "login" => "santarem",
                "email" => "edivaldosimaocosta63@gmail.com",
                "password" => "paseec2251",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "SANTAREM",
                "local" => "Santarém",
                "login" => "sizabel",
                "email" => "elisabetcard@gmail.com",
                "password" => "paseec2250",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "SÃO MIGUEL GUAMÁ",
                "local" => "São Miguel do Guamá",
                "login" => "smguama",
                "email" => "edileiaribeiro015@gmail.com",
                "password" => "paseec2252",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ],
            [
                "nome" => "TUCURUÍ",
                "local" => "Tucuruí",
                "login" => "tucurui",
                "email" => "luciamedeirosgoreti@rotmail.com",
                "password" => "paseec2253",
                "ativo" => 1,
                "admin" => 0,
                "criado_em" => "2022-11-06 00:00:00",
            ]
        ];



        foreach ($usuarios as $usuario) {

            $usuarioModel->skipValidation(true)->protect(false)->insert($usuario);

            // Segunda parte.... inserimos o usuário no grupo de UETP

            $grupoUsuarioModel = new \App\Models\GrupoUsuarioModel();


            $grupoUsuario = [
                'grupo_id' => 2,
                'usuario_id' => $usuarioModel->getInsertID(),
            ];

            $grupoUsuarioModel->protect(false)->insert($grupoUsuario);
        }



        echo 'Usuarios semeados com sucesso, com o grupo UETP!';
    }
}
