<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsuarioSeeder extends Seeder
{
    public function run()
    {
        // Primeiramente semeamos os usuários
        $usuarioModel = new \App\Models\UsuarioModel();

        $usuarios = [
            [
                'nome' => 'ITQ/PA/001 – Pedreira ',
                'local' => 'Belém',
                'login' => 'itqpa01',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2204',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/002 - Marambaia',
                'local' => 'Belém',
                'login' => 'itqpa02',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2205',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/003 – Cremação ',
                'local' => 'Belém',
                'login' => 'itqpa03',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2206',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/004 – Ananindeua 7',
                'local' => 'Ananindeua',
                'login' => 'itqpa04',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2207',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/005 – CTMQ ',
                'local' => 'Belém',
                'login' => 'itqpa05',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2208',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/006 – Ananindeua 4',
                'local' => 'Ananindeua',
                'login' => 'itqpa06',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2209',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/007 – Marabá II',
                'local' => 'Marabá',
                'login' => 'itqpa07',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2210',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/008 – Breves',
                'local' => 'Breves',
                'login' => 'itqpa08',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2211',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/009 – Parauapebas ',
                'local' => 'Parauapebas',
                'login' => 'itqpa09',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2212',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/010 – Igarapé Miri',
                'local' => 'Igarapé Miri',
                'login' => 'itqpa10',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2213',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/011 - Itaituba',
                'local' => 'Itaituba',
                'login' => 'itqpa11',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2214',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/012 - Guamá',
                'local' => 'Belém',
                'login' => 'itqpa12',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2215',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/013 – Tapanã ',
                'local' => 'Belém',
                'login' => 'itqpa13',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2216',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/014 – Vigia ',
                'local' => 'Vigia',
                'login' => 'itqpa14',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2217',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/015 - Castanhal',
                'local' => 'Castanhal',
                'login' => 'itqpa15',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2218',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/016 – São Clemente',
                'local' => 'São Clemente',
                'login' => 'itqpa16',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2219',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/017 – Maguary ',
                'local' => 'Belém',
                'login' => 'itqpa17',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2220',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/018 – Barcarena 2',
                'local' => 'Barcarena',
                'login' => 'itqpa18',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2221',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/019 – Parauapebas 2',
                'local' => 'Parauapebas',
                'login' => 'itqpa19',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2222',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/020 – Ponta de Pedras',
                'local' => 'Ponta de Pedras',
                'login' => 'itqpa20',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2223',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/021 – Tomé Açu',
                'local' => 'Tomé Açu',
                'login' => 'itqpa21',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2224',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/022 - Soure',
                'local' => 'Soure',
                'login' => 'itqpa22',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2225',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/023 – Capitão Poço',
                'local' => 'Capitão Poço',
                'login' => 'itqpa23',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2226',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'MQTI/PA/001 - Belém',
                'local' => 'Belém',
                'login' => 'mqtipa01',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2227',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'MQTI/PA/002 - Parauapebas',
                'local' => 'Parauapebas',
                'login' => 'mqtipa02',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2228',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'MQTI/PA/003 - Cametá',
                'local' => 'Cametá',
                'login' => 'mqtipa03',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2229',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/024 - Altamira',
                'local' => 'Altamira',
                'login' => 'altamira',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2230',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ANANINDEUA I',
                'local' => 'Ananindeua',
                'login' => 'ananindeua1',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2231',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ANANINDEUA II',
                'local' => 'Ananindeua',
                'login' => 'ananindeua2',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2232',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ANANINDEUA III',
                'local' => 'Ananindeua',
                'login' => 'ananindeua3',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2233',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ANANINDEUA IV',
                'local' => 'Ananindeua',
                'login' => 'ananindeua4',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2234',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ANANINDEUA V',
                'local' => 'Ananindeua',
                'login' => 'ananindeua5',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2235',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ANTÔNIO BARRETO',
                'local' => 'Belém',
                'login' => 'abarreto',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2236',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'BARCARENA',
                'local' => 'Barcarena',
                'login' => 'barcarena',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2237',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'BUJARU',
                'local' => 'Bjaru',
                'login' => 'bujaru',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2238',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'CAMETÁ',
                'local' => 'Cametá',
                'login' => 'cameta',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2239',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'CTMQ/PA/01',
                'local' => 'Belém',
                'login' => 'ctmqpa1',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2240',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ICOARACI',
                'local' => 'Icoaraci',
                'login' => 'icoaraci',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2241',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'JURUNAS',
                'local' => 'Belém',
                'login' => 'jurunas',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2242',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'MAGUARY',
                'local' => 'Belém',
                'login' => 'maguary',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2243',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'MARABÁ I',
                'local' => 'Marabá',
                'login' => 'maraba1',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2244',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'MARITUBA I',
                'local' => 'Marituba',
                'login' => 'marituba1',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2245',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'PANORAMA XXI',
                'local' => 'Belém',
                'login' => 'panorama',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2246',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'ITQ/PA/025 - Paragominas',
                'local' => 'Paragominas',
                'login' => 'paragominas',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2247',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'REDENÇÃO',
                'local' => 'Redenção',
                'login' => 'redencao',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2248',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'SACRAMENTA',
                'local' => 'Belém',
                'login' => 'sacramenta',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2249',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'SANTAREM',
                'local' => 'Santarém',
                'login' => 'sizabel',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2250',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'SANTA IZABEL',
                'local' => 'Santa Izabel',
                'login' => 'santarem',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2251',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'SÃO MIGUEL DO GUAMÁ',
                'local' => 'São Miguel do Guamá',
                'login' => 'smguama',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2252',
                'criado_em' => '2022-11-06 00:00:00',
            ],
            [
                'nome' => 'TUCURUÍ',
                'local' => 'Tucuruí',
                'login' => 'tucurui',
                'ativo' => 1,
                'admin' => 0,
                'password' => 'paseec2253',
                'criado_em' => '2022-11-06 00:00:00',
            ]


        ];

        foreach ($usuarios as $usuario) {

            $usuarioModel->skipValidation(true)->protect(false)->insert($usuario);
            // Simple Queries
            // $this->db->query('INSERT INTO usuarios (nome, local, login, ativo, admin, password_hash, criado_em) VALUES(:nome:, :local:, :login:, :ativo:, :admin:, :password:, :criado_em:)', $usuario);


            // Segunda parte.... inserimos o usuário no grupo de UETP

            $grupoUsuarioModel = new \App\Models\GrupoUsuarioModel();


            $grupoUsuario = [
                'grupo_id' => 2,
                'usuario_id' => $usuarioModel->getInsertID(),
            ];

            $grupoUsuarioModel->protect(false)->insert($grupoUsuario);
        }



        echo 'Usuarios semeados com sucesso, com o grupo UETP!';
    }
}
