<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AlunosItqSeeder extends Seeder
{
    public function run()
    {
        // Primeiramente semeamos os usuários
        $usuarioModel = new \App\Models\UsuarioModel();

        // $grupoUsuarioModel = new \App\Models\GrupoUsuarioModel();


        $usuarios = [

            [
                'nome' => 'ÁGATA SOARES',
                'local' => 'ANANINDEUA',
                'login' => 'agatatxsoares',
                'email' => 'agatatxsoares@gmail.com',
                'telefone' => '(91)981157904',
                'password' => 'AlunoItq#2214',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ALONSO SILVA DE MORAIS',
                'local' => 'SALINOPOLIS ',
                'login' => 'silvaalonso955',
                'email' => 'silvaalonso955@gmail.com',
                'telefone' => '91989073845',
                'password' => 'AlunoItq#2215',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ANA ADÉLIA DE CASTRO FARIAS PINTO',
                'local' => 'SANTO ANTÔNIO DO TAUÁ',
                'login' => 'adeliafariaspinto68',
                'email' => 'adeliafariaspinto68@gmail.com',
                'telefone' => '91993008656',
                'password' => 'AlunoItq#2216',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ANA PAULA DE OLIVEIRA MACHADO',
                'local' => 'CANAA DOS CARAJÁS',
                'login' => 'anapaulamachado13',
                'email' => 'anapaulamachado13@gmail.com',
                'telefone' => '094991997614',
                'password' => 'AlunoItq#2217',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ANTONIO FABRICIO CARNEIRO DA SILVA',
                'local' => 'NOVA TIMBOTEUA',
                'login' => 'studiomegavox',
                'email' => 'studiomegavox@gmail.com',
                'telefone' => '91987514861',
                'password' => 'AlunoItq#2218',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ANTONIO LUIS VIEIRA DE ALMEIDA',
                'local' => 'CONCORDIA DO PARA',
                'login' => 'alvpessoal',
                'email' => 'a.l.vpessoal@gmail.com',
                'telefone' => '91988666910',
                'password' => 'AlunoItq#2219',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ANTONIO PEDRO FERREIRA DA CONCEICAO',
                'local' => 'SANTO ANTÔNIO DO TAUÁ',
                'login' => 'apedrofconceicao',
                'email' => 'apedrofconceicao@gmail.com',
                'telefone' => '91984204279',
                'password' => 'AlunoItq#2220',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ATTILIO DE FREITAS ANTONINI',
                'local' => 'SALINÓPOLIS',
                'login' => 'attilioantonini29',
                'email' => 'attilioantonini29@hotmail.com',
                'telefone' => '91992245959',
                'password' => 'AlunoItq#2221',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'BEATRIZ DIAS GONÇALVES ',
                'local' => 'CANÃA DOS CARAJAS ',
                'login' => 'goncalvesbeatrizdias',
                'email' => 'goncalvesbeatrizdias@gmail.com',
                'telefone' => '94992455483',
                'password' => 'AlunoItq#2222',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'BENEDITO JUNIOR COSTA TAVARES',
                'local' => 'CANAÃ DOS CARAJÁS',
                'login' => '4junior3',
                'email' => '4junior3@gmail.com',
                'telefone' => '94 984220957',
                'password' => 'AlunoItq#2223',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'CARLOS ALEXANDRE DA SILVA GONÇALVES ',
                'local' => 'CANAÃ DOS CARAJÁS ',
                'login' => 'carlosasg',
                'email' => 'c.alexandreg86@gmail.com',
                'telefone' => '94992489619',
                'password' => 'AlunoItq#2224',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'CAROLINE INGRID DE MIRANDA MELO',
                'local' => 'BELÉM ',
                'login' => 'carolinemelo3',
                'email' => 'carolinemelo3@outlook.com',
                'telefone' => '91981620741',
                'password' => 'AlunoItq#2225',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'CASSIA FERNANDA LIMA DO CARMO',
                'local' => 'SALINOPOLIS ',
                'login' => 'cassiaealexdocarmo250115',
                'email' => 'cassiaealexdocarmo250115@gmail.com',
                'telefone' => '989497083',
                'password' => 'AlunoItq#2226',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'CICERO CARVALHO ROMAO',
                'local' => 'ITUPIRANGA',
                'login' => 'romaocicero561',
                'email' => 'romaocicero561@gmail.com',
                'telefone' => '94988097936',
                'password' => 'AlunoItq#2227',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'CID TADEO SILVA DOS REIS',
                'local' => 'SALINÓPOLIS',
                'login' => 'cidtadeu123',
                'email' => 'cidtadeu123@gmail.com',
                'telefone' => '91 998279211',
                'password' => 'AlunoItq#2228',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'CLARICE DOS ANJOS DE SOUSA MONTEIRO',
                'local' => 'CANAÃ DOS CARAJÁS',
                'login' => 'clariceasm',
                'email' => 'clarice.monteiro1968@yahoo.com',
                'telefone' => '34992169814',
                'password' => 'AlunoItq#2229',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'DARLAN ERIBELTO DE JESUS PIMENTEL',
                'local' => 'SANTARÉM NOVO',
                'login' => 'darlanpimentel722',
                'email' => 'darlanpimentel722@gmail.com',
                'telefone' => '984605283',
                'password' => 'AlunoItq#2230',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'DELMA SANDOLI PEREIRA DO LAGO',
                'local' => 'SANTO ANTÔNIO DO TAUÁ',
                'login' => 'delmasandoli6130',
                'email' => 'delmasandoli6130@gmail.com',
                'telefone' => '91992165757',
                'password' => 'AlunoItq#2231',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'DIEIGUE RODRIGUES DOS SANTOS',
                'local' => 'ITUPIRANGA',
                'login' => 'rodriguesdieigue',
                'email' => 'rodriguesdieigue@gmail.com',
                'telefone' => '94996667298',
                'password' => 'AlunoItq#2232',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'DUCIRENE DE MELO SILVA',
                'local' => 'SENADOR JOSÉ PORFIRIO',
                'login' => 'ducemelodilva',
                'email' => 'ducemelodilva@gmail.com',
                'telefone' => '93991426640',
                'password' => 'AlunoItq#2233',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'EDINETE DE SOUSA COSTA',
                'local' => 'ITUPIRANGA',
                'login' => 'pastoraedinetedesousa',
                'email' => 'pastoraedinetedesousa@gmail.com',
                'telefone' => '94988034657',
                'password' => 'AlunoItq#2234',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ELIANA TEIXEIRA DANTAS',
                'local' => 'SANTO ANTÔNIO DO TAUÁ',
                'login' => 'elianateixeiradantas78',
                'email' => 'elianateixeiradantas78@gmail.com',
                'telefone' => '91993812002',
                'password' => 'AlunoItq#2235',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ELITON MAICON CARMO SILVA',
                'local' => 'SÃO JOÃO DE PIRABAS ',
                'login' => 'glaucimcs1990',
                'email' => 'glaucimcs1990@gmail.com',
                'telefone' => '91993837245',
                'password' => 'AlunoItq#2236',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ELIZONETE FERREIRA DOS SANTOS FARIAS',
                'local' => 'ITAITUBA ',
                'login' => 'elizonete89',
                'email' => 'elizonete89@gmail.com',
                'telefone' => '93 99142-2490 ',
                'password' => 'AlunoItq#2237',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'FRANCISCO EDER PEREIRA AMARAL',
                'local' => 'NOVA TIMBOTEUA ',
                'login' => 'eder121130',
                'email' => 'eder121130@gmail.com',
                'telefone' => '91981708372',
                'password' => 'AlunoItq#2238',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'GECIONY SILVA MOTA ',
                'local' => 'CANAÃ DOS CARAJÁS',
                'login' => 'gecyonymota',
                'email' => 'gecyonymota@gmail.com',
                'telefone' => '94984368664',
                'password' => 'AlunoItq#2239',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'GILSON GALVAO DE SOUSA',
                'local' => 'ITAITUBA',
                'login' => 'gilsonsukoi',
                'email' => 'gilsonsukoi@gmail.com',
                'telefone' => '93991653948',
                'password' => 'AlunoItq#2240',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'GISELE SILVA DE ALMEIDA',
                'local' => 'CONCORDIA DO PARA',
                'login' => 'gisellealmeidagsa',
                'email' => 'gisellealmeidagsa@gmail.com',
                'telefone' => '91987678103',
                'password' => 'AlunoItq#2241',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ILDENE DOS SANTOS PRATES',
                'local' => 'MARABÁ',
                'login' => 'ildeneprates',
                'email' => 'ildeneprates@hotmail.com',
                'telefone' => '94 99222-5559',
                'password' => 'AlunoItq#2242',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ILDIS SUELY DE OLIVEIRA SETUBAL',
                'local' => 'CANAA DOS CARAJAS ',
                'login' => 'setubalildis',
                'email' => 'setubalildis@gmail.com',
                'telefone' => '94992861336',
                'password' => 'AlunoItq#2243',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'IRALICE PORTUGUES DE SOUZA',
                'local' => 'SANTO ANTÔNIO DO TAUÁ',
                'login' => 'iraliceportugue',
                'email' => 'iraliceportugue@gmail.com',
                'telefone' => '91985603711',
                'password' => 'AlunoItq#2244',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JANAINA FERNANDA DE MELLO FERREIRA',
                'local' => 'ALTAMIRA',
                'login' => 'fernandaferreirajpdmc',
                'email' => 'fernandaferreirajpdmc@gmail.com',
                'telefone' => '93991879828',
                'password' => 'AlunoItq#2245',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JANIELE DA CONCEICAO FIGUEREDO BRAGA CABRAL',
                'local' => 'SALINOPOLIS ',
                'login' => 'nielybraga1988',
                'email' => 'nielybraga1988@gmail.com',
                'telefone' => '9 8230-3436',
                'password' => 'AlunoItq#2246',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JEFFERSON MONTEIRO SOUZA',
                'local' => 'CANAÃ DOS CARAJÁS',
                'login' => 'jeffersouza22',
                'email' => 'jeffersouza22@hotmail.com',
                'telefone' => '94991572597',
                'password' => 'AlunoItq#2247',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JERRY ADRIANO ARAÚJO DOS SANTOS',
                'local' => 'TUCUMÃ-PA',
                'login' => 'jerryadrianogospel',
                'email' => 'jerryadrianogospel@gmail.com',
                'telefone' => '94 981329043',
                'password' => 'AlunoItq#2248',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JOÃO JERFFESSON FERREIRA DE OLIVEIRA',
                'local' => 'SÃO JOÃO DE PIRABAS',
                'login' => 'ojerffesson',
                'email' => 'ojerffesson@gmail.com',
                'telefone' => '91984365677',
                'password' => 'AlunoItq#2249',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JONH SANTOS SILVA',
                'local' => 'SENADOR JOSE PORFIRIO',
                'login' => 'jonhmaraba',
                'email' => 'jonhmaraba@gmail.com',
                'telefone' => '94991747371',
                'password' => 'AlunoItq#2250',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JOSÉ DOMINGOS DE CARVALHO MACHADO FILHO',
                'local' => 'SÃO JOSÉ DO DIVINO',
                'login' => 'franciscamariarm654',
                'email' => 'franciscamariarm654@gmail.com',
                'telefone' => '86 981289957',
                'password' => 'AlunoItq#2251',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JOSÉ VINICIUS DOS SANTOS ',
                'local' => 'SÃO PAULO ',
                'login' => 'viniciusantos6',
                'email' => 'viniciusantos6@hotmail.com',
                'telefone' => '11 98618-8083 ',
                'password' => 'AlunoItq#2252',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'JUAN FERREIRA SALES DA SILVA',
                'local' => 'CANAÃ DOS CARAJÁS',
                'login' => 'juansales41',
                'email' => 'juansales41@gmail.com',
                'telefone' => '94991572819',
                'password' => 'AlunoItq#2253',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'LANA CRISTINA DA COSTA CORREA',
                'local' => 'SALINOPOLIS ',
                'login' => 'lanacristinadacostacorrea',
                'email' => 'lanacristinadacostacorrea@gmail.com',
                'telefone' => '91984394652',
                'password' => 'AlunoItq#2254',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'LEANDRO EUSTAQUIO VIEIRA BAETA',
                'local' => 'CANAÃ DOS CARAJÁS',
                'login' => 'leandroevb',
                'email' => 'leandro.baeta@yahoo.com.br',
                'telefone' => '94991801771',
                'password' => 'AlunoItq#2255',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'LEONEL FERREIRA DA SILVA JUNIOR',
                'local' => 'CONCEIÇÃO DO ARAGUAIA',
                'login' => 'leonelfsjr',
                'email' => 'leonelfsjr@gmail.com',
                'telefone' => '94993006270',
                'password' => 'AlunoItq#2256',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'LINDALVA DE ALMEIDA SILVA',
                'local' => 'SANTARÉM NOVO ',
                'login' => 'lindalvaas',
                'email' => 'lindalva.5619@gmail.com',
                'telefone' => '91988274934',
                'password' => 'AlunoItq#2257',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'MARCIA BORGES BUENO',
                'local' => 'ITUPIRANGA',
                'login' => 'pastoramarciabueno17',
                'email' => 'pastoramarciabueno17@gmail.com',
                'telefone' => '94999538770',
                'password' => 'AlunoItq#2258',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'MARIA ALDEIDE DE ANDRADE SOUSA',
                'local' => 'ITUPIRANGA',
                'login' => 'aaldeide76',
                'email' => 'aaldeide76@gmail.com',
                'telefone' => '94988065260',
                'password' => 'AlunoItq#2259',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'MARIA FRANCISCA LOPES CANTANHEDE ',
                'local' => 'CANAÃ  DOS CARAJAS',
                'login' => 'franciscalopes1981',
                'email' => 'franciscalopes1981@gmail.com',
                'telefone' => '94992812302',
                'password' => 'AlunoItq#2260',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'MARIA JOSE MORAES DIAS',
                'local' => 'ITAITUBA',
                'login' => 'mzezapoetiza',
                'email' => 'mzezapoetiza@gmail.com',
                'telefone' => '93 991914698',
                'password' => 'AlunoItq#2261',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'MARIA NATÁLIA SERRA PEREIRA ',
                'local' => 'CANAÃ DOS CARAJÁS',
                'login' => 'nathyserra51',
                'email' => 'nathyserra51@gmail.com',
                'telefone' => '94992168432',
                'password' => 'AlunoItq#2262',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'MARIA SOLANGE DE OLIVEIRA SANTOS',
                'local' => 'SANTO ANTÔNIO DO TAUÁ',
                'login' => 'msolos',
                'email' => 'sol.maria8824@gmail.com',
                'telefone' => '91984177822',
                'password' => 'AlunoItq#2263',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'MICHELE GOMES PINTO RESENDE BAÊTA',
                'local' => 'CANAÃ DOS CARAJAS',
                'login' => 'micheligprb',
                'email' => 'micheli.resende@yahoo.com.br',
                'telefone' => '94991556458',
                'password' => 'AlunoItq#2264',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'NEY JACKSON PINHEIRO DE SOUZA',
                'local' => 'ITAITUBA',
                'login' => 'njp_74',
                'email' => 'njp_74@hotmail.com',
                'telefone' => '93 991824475',
                'password' => 'AlunoItq#2265',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'NILSON CARVALHO BOTELHO',
                'local' => 'ALTAMIRA',
                'login' => 'nilsoncarvalhoupa',
                'email' => 'nilsoncarvalhoupa@gmail.com',
                'telefone' => '93 991395290',
                'password' => 'AlunoItq#2266',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'PAULO DE SOUSA SANTOS',
                'local' => 'NOVA TIMBOTEUA',
                'login' => 'paulosantosrs982',
                'email' => 'paulosantosrs982@gmail.com',
                'telefone' => '91 988397642',
                'password' => 'AlunoItq#2267',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'RICARDO LUIZ LOPES',
                'local' => 'CANAÃ DOS CARAJÁS',
                'login' => 'ricocruzlopes',
                'email' => 'ricocruzlopes@gmail.com',
                'telefone' => '31996790290',
                'password' => 'AlunoItq#2268',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ROSA MARIA FREITAS FROZ',
                'local' => 'NOVA TIMBOTEUA',
                'login' => 'rozangelafreitas11975',
                'email' => 'rozangelafreitas11975@gmail.com',
                'telefone' => '91 8207-6684',
                'password' => 'AlunoItq#2269',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ROSANA BRAGA DE SOUZA',
                'local' => 'ITUPIRANGA ',
                'login' => 'rosanabs',
                'email' => 'rosana.owzadia@hotmail.com',
                'telefone' => '94988093181',
                'password' => 'AlunoItq#2270',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'ROSÉLIA COSTA SOARES',
                'local' => 'OURILÂNDIA DO NORTE',
                'login' => 'rosecs',
                'email' => 'rosecs.20@hotmail.com',
                'telefone' => '94 991047542',
                'password' => 'AlunoItq#2271',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'STEPHANIE GABRIELA MOUTINHO PEREIRA',
                'local' => 'BELÉM',
                'login' => 'stephaniemgpereira',
                'email' => 'stephaniemgpereira@icloud.com',
                'telefone' => '91985220640',
                'password' => 'AlunoItq#2272',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'SUÉLEN ROSA FURTADO',
                'local' => 'BARCARENA',
                'login' => 'assistentesocialsuelenrosa',
                'email' => 'assistentesocialsuelenrosa@gmail.com',
                'telefone' => '91992621538',
                'password' => 'AlunoItq#2273',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'VALÉRIA FARIAS BAIA MIRANDA',
                'local' => 'BELÉM ',
                'login' => 'mirandaval',
                'email' => 'mirandaval.2019@gmail.com',
                'telefone' => '91991300161',
                'password' => 'AlunoItq#2274',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ],
            [
                'nome' => 'VILSON SILVA DA MATA',
                'local' => 'PARAUAPEBAS',
                'login' => 'psiquevilsondamata',
                'email' => 'psiquevilsondamata@gmail.com',
                'telefone' => '94991171680',
                'password' => 'AlunoItq#2275',
                'ativo' => true,
                'admin' => false,
                'criado_em' => '2022-11-20 13:34:01',
            ]

        ];



        foreach ($usuarios as $usuario) {

            $usuarioModel->skipValidation(true)->protect(false)->insert($usuario);

            // Segunda parte.... inserimos o usuário no grupo de UETP

            $grupoUsuarioModel = new \App\Models\GrupoUsuarioModel();


            $grupoUsuario = [
                'grupo_id' => 4,
                'usuario_id' => $usuarioModel->getInsertID(),
            ];

            $grupoUsuarioModel->protect(false)->insert($grupoUsuario);
        }



        echo 'Usuarios semeados com sucesso, com o grupo Aluno!';
    }
}
